language: cpp
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew install llvm"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build && cd build

script:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake -C ../macos-brewed-clang.txt -DCMAKE_BUILD_TYPE=Release ..
    else
      cmake -DCMAKE_BUILD_TYPE=Release ..
    fi
  - make && ./tests
